export const ColorLightMode = {
  PrimaryColor: "#fff",
  SecondaryColor: "#000",
  BorderColor: "#010101",
  GoldColor: "#B46FAE",
  SectionColor: "#8D3D72",
  MajorColor: "#1B2D6B",
  HeroGeneral: "#2584F4",
  InputColorBorder: "#F2F8FE",
  HeroOneColor: "#4BA1EA",
  HeroTwoColor: "#47D7ED",
  FooterTextColor: "#62F0D5",
  FooterBorderColor: "#2EB4DC",
  PrimColor: "#e8effe",
};
